module.exports = [
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'script-src': ["'self'", 'editor.unlayer.com', '*.tinymce.com', '*.tiny.cloud', 'https:'],
          'frame-src': ["'self'", 'editor.unlayer.com'],
          'connect-src': ["'self'", 'https:', '*.tinymce.com', '*.tiny.cloud', 'blob:'],
          'img-src': [
            "'self'",
            '*.tinymce.com',
            '*.tiny.cloud',
            'data:',
            'blob:',
            'res.cloudinary.com',
            'cdn.jsdelivr.net',
            'strapi.io',
            's3.amazonaws.com',
          ],
          'media-src': [
            "'self'",
            'data:',
            'blob:',
            'res.cloudinary.com',
            "'unsafe-inline'",
            '*.tinymce.com',
            '*.tiny.cloud',
          ],
          'font-src': ["'self'", '*.tinymce.com', '*.tiny.cloud'],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
