version: '3'
services:
  ilearned_postgres:
    container_name: ilearned_postgres
    image: postgres:14
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - '5433:5432'
    volumes:
      - ./backend/db:/var/lib/postgresql/data
