[build]
	base = "frontend/"
	publish = ".next"
	command = "npm run build"

[context.production]
	environment = {NEXT_PUBLIC_STRAPI_API_URL = "https://ilearned-prod.herokuapp.com"}

[context.branch-deploy]
  command = "npm run noIndex"
[context.branch-deploy.environment]
	NEXT_PUBLIC_STRAPI_API_URL = "https://ilearned-staging.herokuapp.com"
	NODE_ENV = "development"

[context.deploy-preview]
	command = "netlify env set NEXT_PUBLIC_STRAPI_API_URL 'https://ilearned-pr-$REVIEW_ID.herokuapp.com' npm run noIndex && node ./setApiUrl.js"
[context.deploy-preview.environment]
	NODE_ENV = "development"

[context.staging]
	command = "npm run noIndex"
[context.staging.environment]
	NEXT_PUBLIC_STRAPI_API_URL = "https://ilearned-staging.herokuapp.com"
	NODE_ENV = "development"


[[plugins]]
	package = "@netlify/plugin-nextjs"