[build]
	base = "frontend/"
	publish = ".next"
	command = "npm run build"

[context.production]
	environment = {NEXT_PUBLIC_STRAPI_API_URL = "https://ilearned-staging.herokuapp.com"}

[context.branch-deploy]
  command = "npm run noIndex"
[context.branch-deploy.environment]
	NEXT_PUBLIC_STRAPI_API_URL = "https://ilearned-staging.herokuapp.com"

[context.deploy-preview]
	command = "npm run noIndex"
[context.deploy-preview.environment]
	NEXT_PUBLIC_STRAPI_API_URL = "https://ilearned-pr-26.herokuapp.com"

[context.master]
	command = "npm run noIndex"
[context.master.environment]
	NEXT_PUBLIC_STRAPI_API_URL = "https://ilearned-staging.herokuapp.com"


[[plugins]]
	package = "@netlify/plugin-nextjs"
[[plugins]]
	package = 'netlify-plugin-contextual-env'
  [plugins.inputs]
  mode = 'prefix'
