[build]
	base = "frontend/"
	publish = ".next"
	command = "npm run build"

[context.production]
	environment = {NEXT_PUBLIC_STRAPI_API_URL = "https://ilearned-staging.herokuapp.com"}

[context.deploy-preview]
	command = "npm run noIndex"
[context.deploy-preview.environment]
	NEXT_PUBLIC_STRAPI_API_URL = "https://ilearned-pr-20.herokuapp.com"
	NODE_ENV = "development"

[context.master]
	command = "npm run noIndex"
[context.master.environment]
	NEXT_PUBLIC_STRAPI_API_URL = "https://ilearned-staging.herokuapp.com"

[functions]
	directory = "./utils/functions"

[[plugins]]
	package = "@netlify/plugin-nextjs"
[[plugins]]
	package = './plugins/netlify-plugin-env-var-by-context'
