name: Deploy Dokku Staging App

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - staging
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  staging_dokku:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@ilearned-staging.ilearnedathing.com:22/ilearned-staging'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  staging_netlify:
    needs: staging_dokku
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to netlify
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_ID_STAGING }}
