name: Deploy Netlify Staging App

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - staging
    paths-ignore:
      - 'backend/**'
  workflow_dispatch:

jobs:
  staging_netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to netlify
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          npm --version && node --version

          cd frontend && yarn install

          cd ../

          npm i -D netlify-cli

          netlify deploy --build --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --site ${{secrets.NETLIFY_SITE_ID}} --message "Deployed staging from github actions" --context branch-deploy --alias staging
