name: Get PR Number and Save to Artifact

on:
    pull_request:
        types: [opened, edited]
        branches:
            - 'master'
    workflow_dispatch:

jobs:
    save_pr_number:
        runs-on: ubuntu-latest
        steps:
            - name: Save PR Number in artifact
              shell: bash
              env:
                  PULL_REQUEST_NUMBER: ${{github.event.number}}
              run: echo $PULL_REQUEST_NUMBER > pull_request_number.txt

            - name: Upload the PULL REQUEST number
              uses: actions/upload-artifact@v2
              with:
                  name: pull_request_number
                  path: ./pull_request_number.txt
