name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronized']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - run: npm --version && node --version
      - run: yarn
      - run: yarn build
      - run: yarn add -D netlify-cli
      - run: npx netlify-cli status
