name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronized']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm --version && node --version
      - run: npm install
      - run: cd frontend && npm install
      - run: cd ../
      - run: npm i -D netlify-cli
      - run: npx netlify-cli status
