name: 'Netlify Preview Deploy'

on:
  workflow_run:
    workflows: ["Check deployment status"]
    types:
      - completed
  # pull_request:
  #   types: ['opened', 'edited', 'synchronized']
  workflow_dispatch:

jobs:
  on-heroku-deploy-sucess:
    runs-on: ubuntu-18.04
    # if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - uses: actions/checkout@v1
      # Find the PR associated with this push, if there is one.
      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
      - run: echo "PR Number = ${{steps.pr.outputs.pull_request_number}}"
#       - run: npm --version && node --version
#       - run: cd frontend && npm install
#       - run: cd ../
#       - run: npm i -D netlify-cli
#       - run: sed -i "s~https://ilearned-pr-.*~https://ilearned-pr-$(echo ${{ steps.findPr.outputs.pr }}).herokuapp.com\"~g" netlify.toml
#       - run: cat netlify.toml
#       - run: netlify deploy --build --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --site ${{secrets.NETLIFY_SITE_ID}} --alias deploy-preview-$(echo ${{ steps.findPr.outputs.pr }}) --context deploy-preview
  on-heroku-deploy-failure:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - run: echo 'The triggering workflow failed'
