name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronized']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm --version && node --version
      - run: cd frontend && npm install
      - run: cd ../
      - run: npm i -D netlify-cli
      - run: sed "s/https://ilearned-pr-.*/https://ilearned-pr-$(echo ${{github.event.pull_request_number}}).herokuapp.com/g" netlify.toml
      - run: netlify deploy --build --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --site ${{secrets.NETLIFY_SITE_ID}} --context deploy-preview
