name: 'Netlify Preview Deploy'

on:
    workflow_run:
        workflows: ['Check deployment status']
        types:
            - completed
    workflow_dispatch:

jobs:
    on-heroku-deploy-sucess:
        runs-on: ubuntu-18.04
        if: ${{github.event.workflow_run.conclusion == 'success'}}
        steps:
            - uses: actions/checkout@v1
            # Find the PR associated with this push, if there is one.
            - name: Download workflow artifact (PR Number)
              uses: dawidd6/action-download-artifact@v2.11.0
              with:
                  name: pull_request_number
                  workflow: get-pr-number.yml
                  run_id: ${{ github.event.workflow_run.id }}
                  search_artifacts: true

            - name: Read the PR number from file
              id: pr
              uses: juliangruber/read-file-action@v1.0.0
              with:
                  path: ./pull_request_number/pull_request_number.txt
            - run: echo "PR Number = ${{steps.pr.outputs.content}}"
            - run: npm --version && node --version
            - run: cd frontend && npm install
            - run: cd ../
            - run: npm i -D netlify-cli
            - run: sed -i "s~https://ilearned-pr-.*~https://ilearned-pr-$(echo ${{ steps.pr.outputs.content }}).herokuapp.com\"~g" netlify.toml
            - run: cat netlify.toml
            - run: netlify deploy --build --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --site ${{secrets.NETLIFY_SITE_ID}} --alias deploy-preview-$(echo ${{ steps.pr.outputs.content }}) --context deploy-preview
    on-heroku-deploy-failure:
        runs-on: ubuntu-latest
        if: ${{github.event.workflow_run.conclusion == 'failure'}}
        steps:
            - run: echo 'The triggering workflow failed'
